# Generated by Django 3.2.4 on 2021-07-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
    ]
