# Generated by Django 3.2.4 on 2021-07-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20210701_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
    ]
