# Generated by Django 3.2.4 on 2021-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_remove_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
    ]
